# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-python:latest"
  armhf: "ghcr.io/home-assistant/armhf-base-python:latest"
  armv7: "ghcr.io/home-assistant/armv7-base-python:latest"
  i386: "ghcr.io/home-assistant/i386-base-python:latest"
labels:
  org.opencontainers.image.title: "SMA Energy Meter emulator"
  org.opencontainers.image.description: "Emulate the existence of one or more SMA Energy Meters on the local network."
  org.opencontainers.image.source: "https://github.com/Roeland54/SMA-Energy-Meter-emulator"
  org.opencontainers.image.licenses: "Apache License 2.0"
