name: "SMA Energy Meter emulator"
description: "Simulate one or more SMA energy meters based on mqtt messages."
version: "0.0.7"
slug: sma
url: "https://github.com/Roeland54/SMA-Energy-Meter-emulator"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
services:
  - "mqtt:need"
options:
  enable_mqtt: true
  mqtt:
    broker: "auto_broker"
    port: "auto_port"
    username: "auto_user"
    password: "auto_password"
  debug_logging: false
  disable_logging: false
schema:
  enable_mqtt: bool
  mqtt:
    broker: str
    port: str
    username: str?
    password: str?
  debug_logging: bool
  disable_logging: bool
image: "ghcr.io/roeland54/{arch}-sma-energy-meter-emulator"
